modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "zapinators"
version = "${version}"
displayName = "Zapinators"
authors = "Namefix"
description = '''
Adds the laser guns from Terraria
'''
logoFile = "assets/zapinators/icon.png"

[[dependencies.zapinators]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zapinators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zapinators]]
modId = "architectury"
type = "required"
versionRange = "[15.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.zapinators]]
modId = "resourcefulconfig"
type = "required"
versionRange = "[3.4.3,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "zapinators.mixins.json"
