modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Namefix/Zapinators/issues"
license = "GPL-3.0"

[[mods]]
modId = "zapinators"
version = "${version}"
displayName = "Zapinators"
authors = "Namefix"
description = '''
Experience Terraria's iconic arsenal in the style of Minecraft!

From zapinators of every color to laser rifles, from bee guns to gem staves, Zapinators brings (and will continue to bring) an exciting collection of Terraria-inspired weapons and equipment.
'''
logoFile = "assets/zapinators/icon.png"

[[dependencies.zapinators]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.84,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zapinators]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.zapinators]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.zapinators]]
modId = "resourcefulconfig"
type = "required"
versionRange = "[3.0.9,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "zapinators.mixins.json"
